version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]  # Ensure FastAPI runs
  sparql:
    build: ./backend
    depends_on:
      - backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app/sparql_endpoint.py"]
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  #  Mount frontend source code for live updates
      - /app/node_modules  #  Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm start  #  Ensure frontend runs in watch mode
